### ISSUE TITLE
feat:  Accept and reject travel

### ISSUE THREAD

**Issue by romaniam** [romaniam/cap-sflight#23]
Estimation: 5

## Acceptance Criteria
- [ ] I can view a list of travel bookings
- [ ] I can accept or reject a travel booking
- [ ] When a booking is accepted, it is marked as 'Accepted' in the system
- [ ] When a booking is rejected, it is marked as 'Rejected' in the system

## Implementation Steps
 - Create a new UI page to display the list of travel bookings
- Fetch the travel bookings data from the backend API
- Display the list of travel bookings in a table format
- Add a button or dropdown option for each travel booking to accept or reject it
- Handle the accept or reject action in the frontend by sending a request to the backend API
- Update the status of the travel booking in the database based on the accept or reject action

## Architecture
```mermaid
sequenceDiagram
    participant User
    participant System
    participant Database
    
    User->>System: View travel bookings
    System->>Database: Retrieve travel bookings
    Database-->>System: Return travel bookings
    System-->>User: Display travel bookings
    
    User->>System: Accept travel booking
    System->>Database: Mark booking as accepted
    Database-->>System: Update booking status
    System-->>User: Confirm booking acceptance
    
    User->>System: Reject travel booking
    System->>Database: Mark booking as rejected
    Database-->>System: Update booking status
    System-->>User: Confirm booking rejection

```
