### ISSUE TITLE
feat:  Accept or reject travel

### ISSUE THREAD

**Issue by romaniam** [romaniam/cap-sflight#24]
Estimation: 8

## Acceptance Criteria
- [ ] I should be able to see the details of the travel booking
- [ ] I should be able to accept or reject the booking
- [ ] If I accept the booking, the travel status should be updated to 'Accepted'
- [ ] If I reject the booking, the travel status should be updated to 'Rejected'

## Implementation Steps
 - Retrieve the travel booking details from the database
- Display the travel booking details on the UI
- Add 'Accept' and 'Reject' buttons on the UI
- Handle the click event of the 'Accept' button
- Update the travel status to 'Accepted' in the database
- Handle the click event of the 'Reject' button
- Update the travel status to 'Rejected' in the database

## Architecture
```mermaid
sequenceDiagram
    participant User
    participant Software Architect
    participant Developer
    participant Travel Booking System
    participant Database

    User->>Travel Booking System: Make Travel Booking
    Travel Booking System->>Developer: Notify New Booking
    Developer-->>Database: Retrieve Travel Booking Details
    Database-->>Developer: Return Travel Booking Details
    Developer-->>Software Architect: Request Update
    Software Architect-->>Developer: Provide Update Instructions
    Developer->>Travel Booking System: Update Travel Status
    Travel Booking System-->>Database: Update Travel Status
    loop Until Decided
        Developer-->>Software Architect: Request Decision
        Software Architect-->>Developer: Provide Decision
    end
    Developer->>Travel Booking System: Update Travel Status
    Travel Booking System-->>Database: Update Travel Status
    Travel Booking System-->>User: Notify Booking Update

```
