### ISSUE TITLE
feat:  Accept or reject travel

### ISSUE THREAD

**Issue by romaniam** [romaniam/cap-sflight#25]
Estimation: 8

## Acceptance Criteria
- [ ] I can only accept or reject a travel booking if I have the 'reviewer' scope.
- [ ] When I accept a travel booking, the booking status should be updated to 'accepted'.
- [ ] When I reject a travel booking, the booking status should be updated to 'rejected'.
- [ ] Both accepted and rejected bookings should be recorded in the database with the corresponding status.

## Implementation Steps
 - Check if the current user has the 'reviewer' scope.
- If the user doesn't have the 'reviewer' scope, display an error message.
- If the user has the 'reviewer' scope, show the list of travel bookings.
- For each travel booking, display the booking details and provide buttons to accept or reject the booking.
- When the accept button is clicked, update the booking status to 'accepted' and record the change in the database.
- When the reject button is clicked, update the booking status to 'rejected' and record the change in the database.
- Display a success message after accepting or rejecting a booking.

## Architecture
```mermaid
sequenceDiagram
    participant User
    participant Backend
    participant Database

    User->>Backend: Submit Travel Booking
    Backend->>Backend: Validate User Scope
    alt User has 'reviewer' scope
        Backend->>Backend: Update Booking Status to 'accepted'
        Backend->>Database: Save Booking with status 'accepted'
        Backend->>Backend: Notify User of Successful Booking Acceptance
    else
        Backend->>Backend: Update Booking Status to 'rejected'
        Backend->>Database: Save Booking with status 'rejected'
        Backend->>Backend: Notify User of Rejected Booking
    end
    Backend->>User: Response
```
