### ISSUE TITLE
feat:  Accept or reject travel

### ISSUE THREAD

**Issue by romaniam** [romaniam/cap-sflight#26]
Estimation: 8

## Acceptance Criteria
- [ ] Only users with reviewer scope can trigger the accept or reject action
- [ ] If accepted, the travel booking status should be updated to 'Accepted'
- [ ] If rejected, the travel booking status should be updated to 'Rejected'

## Implementation Steps
 - Check if the user has the 'reviewer' scope
- Fetch the travel booking using the provided UUID
- Display the details of the travel booking
- Add accept and reject buttons to the UI
- Implement the logic to update the travel booking status to 'Accepted' or 'Rejected' based on user selection
- Display a success message and refresh the UI to reflect the updated status

## Architecture
```mermaid
sequenceDiagram
    participant User
    participant Frontend as Frontend (SAP UI5 and Fiori Elements)
    participant Backend as Backend (SAP CAP with OData Endpoints)
    participant SaaS as SaaS (SAP BTP)
    participant HANA as HANA Cloud
    
    Note over User: User triggers accept/reject action
    User->>Frontend: Trigger accept/reject action
    Frontend->>Backend: Send accept/reject request
    Backend->>SaaS: Forward accept/reject request
    SaaS->>HANA: Update travel booking status
    
    alt accepted
        HANA-->>SaaS: Update travel booking status to Accepted
        SaaS-->>Backend: Send response
        Backend-->>Frontend: Send response
        Frontend-->>User: Show acceptance message
    else rejected
        HANA-->>SaaS: Update travel booking status to Rejected
        SaaS-->>Backend: Send response
        Backend-->>Frontend: Send response
        Frontend-->>User: Show rejection message
    end

```
