### ISSUE TITLE
feat:  Accept or reject travels

### ISSUE THREAD

**Issue by romaniam** [romaniam/cap-sflight#27]
Estimation: 8

## Acceptance Criteria
- [ ] User must have 'reviewer' scope to trigger the actions
- [ ] The system must update the travel status to 'accepted' or 'rejected' based on the action
- [ ] The system must send a notification to the traveler about the status of their travel

## Implementation Steps
 - Implement UI component to display the travel details and accept/reject buttons
- Validate if the user has 'reviewer' scope before allowing them to trigger the action
- Upon accepting the travel, update the travel status to 'accepted' in the database
- Upon rejecting the travel, update the travel status to 'rejected' in the database
- Send a notification to the traveler about the status of their travel

## Architecture
```mermaid
sequenceDiagram
    participant User as U
    participant Processor as P
    participant SaaS Application as A
    participant SAP UI5 and Fiori Elements as F
    participant OData as O
    participant HANA Cloud as H
    participant Notification Service as N
 
    activate User
    User->>F: Reviewer action
    activate F
    F->>P: Request to update travel status
    activate P
    P->>A: Update travel status
    activate A
    A->>O: OData request to update status
    activate O
    O->>H: Persist updated status
    activate H
    H->>+N: Send notification to traveler
    activate N
    N-->>-H: Confirmation of notification sent
    deactivate N
    H-->>-O: Confirmation of status update
    deactivate H
    O-->>-A: Confirmation of status update
    deactivate O
    A-->>-P: Confirmation of status update
    deactivate A
    P-->>-F: Confirmation of status update
    deactivate P
    F-->>-User: Confirmation of status update
    deactivate F
    deactivate User
```
