### ISSUE TITLE
feat:  Allow flights batch processing

### ISSUE THREAD

**Issue by romaniam** [romaniam/cap-sflight#28]
Estimation: 8

## Acceptance Criteria
- [ ] I can select multiple flights at once
- [ ] I can process the selected flights in bulk
- [ ] I receive a confirmation message after successful batch processing

## Implementation Steps
 - Add a checkbox column in the flight list table
- Implement select/deselect all functionality in the checkbox column
- Implement a button to initiate batch processing
- When the batch processing button is clicked, gather all selected flights
- Send a request to the server to process the selected flights in the backend
- Display a loading spinner while the batch processing is in progress
- Once the batch processing is completed, display a success message with the number of flights processed
- Update the flight list table to reflect the changes after batch processing

## Architecture
```mermaid
sequenceDiagram
    participant FrontendLayer
    participant ServiceLayer
    participant HANACloud
    participant Processor

    Note left of FrontendLayer: User selects flights
    FrontendLayer->>ServiceLayer: Send selected flights data
    ServiceLayer->>HANACloud: Persist selected flights data
    ServiceLayer->>FrontendLayer: Return confirmation message
    Note right of FrontendLayer: User receives confirmation message
    FrontendLayer->>Processor: Send selected flights data
    Processor->>ServiceLayer: Process selected flights data in bulk
    ServiceLayer->>HANACloud: Update processed flights data
    ServiceLayer->>Processor: Return confirmation message
    Note right of Processor: Processor receives confirmation message
```
