### ISSUE TITLE
feat:  Show customer information in popover

### ISSUE THREAD

**Issue by romaniam** [romaniam/cap-sflight#29]
Estimation: 8

## Acceptance Criteria
- [ ] Only admins should have access to this feature.
- [ ] Clicking on the customer's name should display the popover.
- [ ] The popover should show the customer's email and phone number.

## Implementation Steps
 - Create a new UI component for the popover.
- Retrieve customer information from the database.
- Implement authorization logic to restrict access to admins only.
- Display the customer information in the popover.
- Handle the event when the customer's name is clicked.
- Test the feature to ensure it functions as expected.

## Architecture
```mermaid
sequenceDiagram
    participant Frontend as SAP UI5 and Fiori Elements
    participant Processor as Processor
    participant Service as OData Service
    participant HANA-Cloud as HANA-Cloud

    Frontend->>Processor: Send request to process flights
    loop Authorization
        Processor->>Service: Authenticate admin user
        alt Invalid Admin
            Service-->>Processor: Return unauthorized status
            Processor-->>Frontend: Return unauthorized response
            break
        end
    end
    Processor->>Service: Retrieve flight data
    Service-->>HANA-Cloud: Get flights from HANA-Cloud
    HANA-Cloud-->>Service: Return flight data
    Service-->>Processor: Return flight data
    Processor-->>Frontend: Return flight data
    Frontend->>Processor: Click on customer's name
    Processor->>Service: Retrieve customer information
    Service-->>Processor: Return customer information
    Processor-->>Frontend: Display popover with customer details
    Frontend->>Processor: Close popover
    Processor-->>Frontend: Close popover
```
