### ISSUE TITLE
feat:  Automatically archive travels older than 1 year

### ISSUE THREAD

**Issue by romaniam** [romaniam/cap-sflight#30]
Estimation: 8

## Acceptance Criteria
- [ ] Travels that have an EndDate older than 1 year should be archived
- [ ] Archived travels should no longer be displayed in the system
- [ ] Archived travels should still be accessible for reporting purposes

## Implementation Steps
 - Create a cron job to run daily
- Query the Travel table for travels that have an EndDate older than 1 year
- Update the travel status of the queried travels to 'Archived'
- Ensure archived travels are no longer displayed in the system
- Ensure archived travels are still accessible for reporting purposes

## Architecture
```mermaid
sequenceDiagram
    participant SaaSApplication as SAP UI5 & Fiori Elements
    participant Processor as Processor
    participant Service as OData Service
    participant HANA-Cloud as HANA-Cloud

    SaaSApplication ->> Processor: Request to process flights
    Processor ->> Service: Query flights from HANA-Cloud
    activate Service
    Service ->> HANA-Cloud: Retrieve flights data
    HANA-Cloud -->> Service: Response with flights data
    deactivate Service
    alt Flights older than 1 year exist
        Processor ->> Service: Archive flights older than 1 year
        activate Service
        Service ->> HANA-Cloud: Archive flights data
        HANA-Cloud -->> Service: Confirmation of archiving
        deactivate Service
        alt Archive successful
            Processor ->> SaaSApplication: Flights processing completed successfully
        else Archive failed
            Processor ->> SaaSApplication: Error occurred during archiving
        end
    else
        Processor ->> SaaSApplication: Flights processing completed successfully
    end

```
