### ISSUE TITLE
feat:  As a processor, I want to be able to accept or reject travel bookings

### ISSUE THREAD

**Issue by romaniam** [romaniam/cap-sflight#31]
Estimation: 5

## Acceptance Criteria
- [ ] Only users with the role 'reviewer' should have access to this functionality
- [ ] The accept or reject action should update the booking status accordingly
- [ ] The user interface should provide clear and intuitive options for accepting or rejecting a travel booking

## Implementation Steps
 - Add a new button or menu option for accepting or rejecting travel bookings in the UI
- Implement the logic to restrict access to users with the 'reviewer' role
- Create an API endpoint to handle the accept or reject action
- Update the booking status in the database when the accept or reject action is performed
- Update the UI to display the updated booking status
- Add validation to ensure that only valid bookings can be accepted or rejected

## Architecture
```mermaid
sequenceDiagram
  participant P as Processor
  participant S as SaaS Application
  participant F as Frontend
  participant D as HANA-Cloud

  activate F
  F->>P: Initiate Accept/Reject Action
  P->>S: Check User Role (Reviewer)
  S->>P: Allow Access
  P->>S: Get Booking Details
  S->>P: Booking Details
  P->>F: Display Booking Details

  activate F
  F->>P: User Decision (Accept/Reject)
  P->>S: Update Booking Status
  S->>P: Updated Booking Status

  alt Accept
    P-->>D: Persist Updated Booking Status
    D-->>P: Acknowledge Update
  else Reject
    P-->S: Display Error Message
  end

  P-->>F: Display Confirmation Message

```
