### ISSUE TITLE
feat:  Accept and reject travels

### ISSUE THREAD

**Issue by romaniam** [romaniam/cap-sflight#33]
Estimation: 13

## Acceptance Criteria
- [ ] Only users with the 'reviewer' role can access this feature.
- [ ] When accepting a travel, the status should be changed to 'Accepted' and an email should be sent to the customer.
- [ ] When rejecting a travel, the status should be changed to 'Rejected' and an email should be sent to the customer.

## Implementation Steps
 - Check if the user has the 'reviewer' role. If not, display an error message.
- Display a list of all pending travel bookings.
- For each travel booking, provide an option to either accept or reject it.
- If the user selects 'Accept', update the travel booking status to 'Accepted' and send an email notification to the customer.
- If the user selects 'Reject', update the travel booking status to 'Rejected' and send an email notification to the customer.

## Architecture
```mermaid
sequenceDiagram
    participant Frontend as SAP UI5 and Fiori Elements
    participant Service as OData Service
    participant Processor as Processor
    participant EmailService as Email Service
    participant HANA as HANA-Cloud
    
    Frontend->>Service: Request flights
    Service->>Processor: Retrieve flights
    Processor->>Service: Return flights
    Service->>Frontend: Show flights
    
    loop User interaction
        Frontend->>Service: Accept travel (flightId)
        Service->>Processor: Accept travel (flightId)
        alt User has 'reviewer' role
            Processor->>HANA: Update status (flightId, 'Accepted')
            alt Send email
                Processor->>EmailService: Send email (customer, 'Accepted')
                EmailService-->>Processor: Email sent
            end
        else Unauthorized access
            Processor-->>Frontend: Unauthorized access error
        end
    end
    
    loop User interaction
        Frontend->>Service: Reject travel (flightId)
        Service->>Processor: Reject travel (flightId)
        alt User has 'reviewer' role
            Processor->>HANA: Update status (flightId, 'Rejected')
            alt Send email
                Processor->>EmailService: Send email (customer, 'Rejected')
                EmailService-->>Processor: Email sent
            end
        else Unauthorized access
            Processor-->>Frontend: Unauthorized access error
        end
    end

```
