### ISSUE TITLE
feat:  Archive flights older than 1 year

### ISSUE THREAD

**Issue by romaniam** [romaniam/cap-sflight#35]
Estimation: 5

## Acceptance Criteria
- [ ] User must have admin permission to access the archive feature
- [ ] Only flights older than 1 year should be archived
- [ ] Archived flights should no longer appear in search results

## Implementation Steps
 - Check user permission before allowing access to archive feature
- Query database for flights older than 1 year
- Move identified flights to archive table
- Update search functionality to exclude archived flights

## Architecture
```mermaid
sequenceDiagram
    participant User
    participant UI5
    participant OData
    participant HANA

    User ->> UI5: Clicks on archive button
    UI5 ->> OData: Request to archive flights
    OData ->> HANA: Query flights older than 1 year
    HANA -->> OData: Returns list of flights to archive
    OData -->> UI5: Success response
    UI5 -->> User: Confirmation message

    User ->> UI5: Performs search
    UI5 ->> OData: Request to search for flights
    OData ->> HANA: Query flights in database
    HANA -->> OData: Returns list of available flights
    OData -->> UI5: Displays search results to User

```
